### ISSUE TITLE
BLE Audio Example

### ISSUE THREAD

**Issue by mrhempman69** [sipeed/M0S_BL616_example#13]
Can you please provide an example of how to set up the device to be used as a BLE Audio acceptor, from a phone connection? And the example can show both how to use I2S on the output, and how to use the DAC on the output too?

Where can i get more information on how to use BLE audio with this chip? I know it will involve using one of the LC3 codec libraries on Github

**Comment by mrhempman69** [comment]
How come they won't support this?

**Comment by gamelaster** [comment]
@mrhempman69 you are asking in wrong repository. Rather ask in Bouffalo SDK repo or at Bouffalo BBS.
